# Generated by Django 4.2.2 on 2023-06-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Брэнд автомобиля',
                'verbose_name_plural': 'Брэнды автомобилей',
            },
        ),
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип кузова автомобиля',
                'verbose_name_plural': 'Типы кузовов автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Цвет автомобиля',
                'verbose_name_plural': 'Цвета автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип топлива автомобиля',
                'verbose_name_plural': 'Типы топлива автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Год выпуска автомобиля')),
                ('is_stock', models.BooleanField(verbose_name='Статус наличия')),
                ('is_customs', models.BooleanField(verbose_name='Статус растаможивания')),
                ('is_deleted', models.BooleanField(verbose_name='Статус удаления')),
                ('year', models.IntegerField(verbose_name='Год выпуска автомобиля')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('horse_powers', models.IntegerField(verbose_name='Лошадиные силы')),
                ('engine', models.CharField(max_length=50, verbose_name='Мотор')),
                ('gear', models.CharField(max_length=50, verbose_name='Коробка передач')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.brand', verbose_name='Брэнд автомобиля')),
                ('car_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.carbody', verbose_name='Тип кузова автомобиля')),
                ('exterior_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.color', verbose_name='Цвет экстерьера автомобиля')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.fuel', verbose_name='Тип топлива автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
