# Generated by Django 4.2.2 on 2023-07-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_car_image_image_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.car', verbose_name='Автомобиль'),
        ),
    ]
