# Generated by Django 4.2.2 on 2023-07-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_image_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='head_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='store.image', verbose_name='Главное фото автомобиля'),
        ),
    ]
