# Generated by Django 4.2.2 on 2023-07-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_car_head_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='head_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
    ]
