# Generated by Django 4.2.2 on 2023-09-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_car_head_image_remove_image_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
