# Generated by Django 4.2.2 on 2023-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='youtube_url',
            field=models.CharField(default='', max_length=100, verbose_name='Ссылка на видеообзор'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
