# Generated by Django 4.2.2 on 2023-09-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_car_youtube_url_alter_car_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Привод', max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип наддува',
                'verbose_name_plural': 'Типы наддувов',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип привода',
                'verbose_name_plural': 'Типы приводов',
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип коробки автомобиля',
                'verbose_name_plural': 'Типы коробки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Length', models.IntegerField(null=True, verbose_name='Длина автомобиля')),
                ('width', models.IntegerField(null=True, verbose_name='Ширина автомобиля')),
                ('height', models.IntegerField(null=True, verbose_name='Высота автомобиля')),
                ('wheelbase', models.IntegerField(null=True, verbose_name='Колёсная база')),
                ('clearance', models.CharField(max_length=10, null=True, verbose_name='Клиренс')),
                ('rear_front_width', models.IntegerField(null=True, verbose_name='Ширина передней колеи')),
                ('rear_track_width', models.IntegerField(null=True, verbose_name='Ширина задней колеи')),
                ('wheel_size', models.CharField(max_length=10, null=True, verbose_name='Размер колёс')),
            ],
            options={
                'verbose_name': 'Размер автомобиля',
                'verbose_name_plural': 'Размеры автомобилей',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gear',
        ),
        migrations.RemoveField(
            model_name='car',
            name='horse_powers',
        ),
        migrations.AlterField(
            model_name='fuel',
            name='title',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('horse_powers', models.IntegerField(null=True, verbose_name='Лошадиные силы')),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Объем двигателя')),
                ('country', models.CharField(max_length=50, null=True, verbose_name='Страна марки')),
                ('number_of_doors', models.IntegerField(null=True, verbose_name='Количество дверей')),
                ('number_of_seats', models.IntegerField(null=True, verbose_name='Количество мест')),
                ('wheel_position', models.CharField(max_length=20, null=True, verbose_name='Расположение руля')),
                ('front_suspension', models.CharField(max_length=50, null=True, verbose_name='Тип передней подвески')),
                ('rear_suspension', models.CharField(max_length=50, null=True, verbose_name='Тип задней подвески')),
                ('front_brakes', models.CharField(max_length=50, null=True, verbose_name='Передние тормоза')),
                ('rear_brakes', models.CharField(max_length=50, null=True, verbose_name='Задние  тормоза')),
                ('max_speed', models.IntegerField(null=True, verbose_name='Максимальная скорость')),
                ('acceleration', models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Разгон автомобиля')),
                ('fuel_consumption', models.CharField(max_length=50, null=True, verbose_name='Расход топлива')),
                ('environmental_class', models.CharField(max_length=20, null=True, verbose_name='Экологический класс')),
                ('trunk_volume', models.CharField(max_length=20, null=True, verbose_name='Объем багажника')),
                ('fuel_tank_volume', models.IntegerField(null=True, verbose_name='Объём топливного бака')),
                ('curb_weight', models.IntegerField(null=True, verbose_name='Снаряженная масса')),
                ('full_mass', models.IntegerField(null=True, verbose_name='Полная  масса')),
                ('torque', models.IntegerField(null=True, verbose_name='Крутящий момент')),
                ('number_of_cylinders', models.IntegerField(null=True, verbose_name='Количество цилиндров')),
                ('number_of_gears', models.IntegerField(null=True, verbose_name='Количество передач')),
                ('boost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.boost', verbose_name='Тип наддува')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.drive', verbose_name='Тип привода')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.fuel', verbose_name='Тип топлива')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.gear', verbose_name='Вид коробки автомобиля')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.size', verbose_name='Размеры автомобиля')),
            ],
            options={
                'verbose_name': 'Детальные характеристики автомобиля',
                'verbose_name_plural': 'Детальные характеристики автомобиля',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='characteristics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.characteristics', verbose_name='Детальные характеристики'),
        ),
    ]
