# Generated by Django 4.2.2 on 2023-09-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_boost_drive_gear_size_remove_car_engine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristics',
            name='model',
        ),
        migrations.AlterField(
            model_name='boost',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
    ]
