# Generated by Django 4.2.2 on 2023-09-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_length_size_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Страна марки',
                'verbose_name_plural': 'Страны марок',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Экологический класс',
                'verbose_name_plural': 'Экологические классы',
            },
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.country', verbose_name='Страна марки'),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='environmental_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='store.environmentalclass', verbose_name='Экологический класс'),
        ),
    ]
