# Generated by Django 4.2.2 on 2023-09-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_country_environmentalclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Наименование'),
        ),
    ]
