# Generated by Django 4.2.2 on 2023-09-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_country_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='rear_front_width',
            new_name='front_track_width',
        ),
    ]
