# Generated by Django 4.2.2 on 2023-09-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_rear_front_width_size_front_track_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='Почта клиента')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон клиента')),
                ('is_close', models.BooleanField(verbose_name='Признак обработки заявки')),
            ],
            options={
                'verbose_name': 'Заявка на консультацию',
                'verbose_name_plural': 'Заявки на консультацию',
            },
        ),
    ]
