# Generated by Django 4.2.2 on 2023-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_bid_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='is_close',
            new_name='is_processed',
        ),
        migrations.AlterField(
            model_name='bid',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Телефон клиента'),
        ),
    ]
