# Generated by Django 4.2.2 on 2023-10-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_is_close_bid_is_processed_alter_bid_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='store.car', verbose_name='Интерисующий автомобиль'),
        ),
    ]
