# Generated by Django 4.2.2 on 2023-10-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_bid_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='bid',
            name='date_close_bid',
            field=models.DateField(null=True, verbose_name='Дата закрытия заявки'),
        ),
        migrations.AddField(
            model_name='bid',
            name='date_open_bid',
            field=models.DateField(null=True, verbose_name='Дата открытия заявки'),
        ),
    ]
