# Generated by Django 4.2.2 on 2023-10-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_bid_is_processed_bid_date_close_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='store.car', verbose_name='Интерисующий автомобиль'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_close_bid',
            field=models.DateField(blank=True, null=True, verbose_name='Дата закрытия заявки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_open_bid',
            field=models.DateField(blank=True, null=True, verbose_name='Дата открытия заявки'),
        ),
    ]
